"""Инициализация моделей

Revision ID: 2d0dd9d7c289
Revises: 
Create Date: 2025-05-01 23:13:44.260802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d0dd9d7c289'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('p_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('img', postgresql.BYTEA(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pereval_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_parent', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spr_activities_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('fam', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('otc', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('pereval_added',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('beautyTitle', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('other_titles', sa.String(length=255), nullable=True),
    sa.Column('connect', sa.String(length=255), nullable=True),
    sa.Column('add_time', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('coord_id', sa.Integer(), nullable=False),
    sa.Column('level_winter', sa.String(length=6), nullable=True),
    sa.Column('level_summer', sa.String(length=6), nullable=True),
    sa.Column('level_autumn', sa.String(length=6), nullable=True),
    sa.Column('level_spring', sa.String(length=6), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False, server_default='1'),
    sa.ForeignKeyConstraint(['coord_id'], ['coords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pereval_images',
    sa.Column('pereval_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.TIMESTAMP(), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['p_images.id'], ),
    sa.ForeignKeyConstraint(['pereval_id'], ['pereval_added.id'], ),
    sa.PrimaryKeyConstraint('pereval_id', 'image_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pereval_images')
    op.drop_table('pereval_added')
    op.drop_table('users')
    op.drop_table('spr_activities_types')
    op.drop_table('pereval_areas')
    op.drop_table('p_images')
    op.drop_table('coords')
    # ### end Alembic commands ###
