"""в модель PerevalAdded добавить поле creator_id

Revision ID: c801a7aeb3a6
Revises: 7b84bc439dec
Create Date: 2025-05-02 16:33:29.922946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c801a7aeb3a6'
down_revision: Union[str, None] = '7b84bc439dec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pereval_added', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'pereval_added', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pereval_added', type_='foreignkey')
    op.drop_column('pereval_added', 'creator_id')
    # ### end Alembic commands ###
