"""в модели PerevalAdded поле beauty_title переименовать в beauty_title

Revision ID: 7b84bc439dec
Revises: 824c9cfce8b0
Create Date: 2025-05-02 15:01:08.725557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b84bc439dec'
down_revision: Union[str, None] = '824c9cfce8b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pereval_added', sa.Column('beauty_title', sa.String(length=255), nullable=False))
    op.drop_column('pereval_added', 'beautyTitle')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pereval_added', sa.Column('beautyTitle', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('pereval_added', 'beauty_title')
    # ### end Alembic commands ###
